[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "prettier" , args = ["--write"] }
language-servers = [ "typescript-language-server" ]

